"""
Contains email logic.
"""
import smtplib
from os.path import basename
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from eex.conf.config import conf




class EmailReport():
    """
    Initialize object to send error report to a configurable list of recipients.
    """

    def __init__(self, report_name):
        """

        :param report_name: name of the error report generated by margin_checker.
        """
        self.report_name = report_name
        self.send_email()


    def send_email(self):
        """
        Sends generated report to configured email addresses.
        :return: None
        """

        subject = "Error Report"
        content = 'Please find attached the error report'

        msg = MIMEMultipart()
        msg['From'] = conf.from_addr
        msg['To'] = ', '.join(conf.to_addr)
        msg['Subject'] = subject
        body = MIMEText(content, 'plain')
        msg.attach(body)


        filename = self.report_name
        with open(filename, 'r') as report:
            part = MIMEApplication(report.read(), Name=basename(filename))
            part['Content-Disposition'] = f'attachment; filename={basename(filename)}'
        msg.attach(part)

        server = smtplib.SMTP_SSL(conf.smtp_server, conf.smtp_server_port)
        server.login(conf.from_addr, conf.password)
        server.send_message(msg, from_addr=conf.from_addr, to_addrs=conf.to_addr)

        server.quit()
